### PR TITLE
Cypress setup

### PR DESCRIPTION
**Pull request by jarrmill**
This pull request addresses [Issue #40](https://github.com/cityofaustin/census2020/issues/40) by adding functionality to run Cypress tests. It was implemented by following the tutorial pasted below:

https://www.gatsbyjs.org/docs/end-to-end-testing/

Using this, we can create new Cypress tests, as well as perform A11y checks (see screenshot below).
Screen Shot 2019-11-24 at 1 22 41 PM

This pull request follows the tutorial very closely, and doesn't add any additional tests. I did take out the example tests, and can take out the other example code if need be. Let me know if I can do anything else, thanks.

### CODE REVIEW

**Comment by dontehightower** [comment]
Nice to see we're including Cypress!

**Review by mateoclarke — COMMENTED** [review]
Could you add a section to the README.md explaining what command line script to run Cypress? And maybe some links for reference on how to add tests?

**Comment by jarrmill** [comment]
@mateoclarke Good catch, I can get that up soon!

**Comment by mateoclarke** [comment]
Cool, @jarrmill. I can go ahead and merge as-is and you can circle back and add the deets for running Cypress in another PR.

**Comment by mateoclarke** [comment]
Closes #40

**Pull request merged**
